version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "fsd_blog_db"
    environment:
      POSTGRES_USER: fsd_blog
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: fsd_blog
      PGDATA: /pgdata
    ports:
      - "54321:5432"
    volumes:
      - ./pgdb_init.sql:/docker-entrypoint-initdb.d/init.sql
      - .pgdata:/pgdata

